platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven

inputs:
- name: SpringBootSimpleRest

run:
  path: sh
  args:
  - -exc
  - |
    cd SpringBootSimpleRest
    mvn package
    ls ./target/*
