platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: SpringBootSimpleRest

run:
  path: sh
  args:
  - -exc
  - |
    cd SpringBootSimpleRest
    ./mvnw package
