platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: '8'

inputs:
- name: SpringBootSimpleRest

run:
  path: sh
  args:
  - -exc
  - |
    cd SpringBootSimpleRest
    mvn package
    pwd
    ls
